plugins {
    id 'java'
    id 'application'
}

description = 'Infection-themed video game developed for high-school senior project'

group 'io.github.slavsquatsuperstar'
version '1.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

dependencies {
    implementation fileTree('libs/greenfoot-main.jar')
}

application {
    mainClass = 'wildfire.WildfireLauncher'
}

tasks {
    wrapper {
        gradleVersion = '9.7.0'
        distributionType = Wrapper.DistributionType.BIN
    }

    jar {
        manifest.attributes 'Main-Class': application.mainClass
        manifest.attributes 'Class-Path': configurations.runtimeClasspath.files.collect { it.absolutePath }.join(' ')
    }
}
