plugins {
    id 'java'
    id 'application'
}

description = 'Infection-themed video game developed for high-school senior project'

group 'io.github.slavsquatsuperstar'
version '1.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

dependencies {
    implementation files('libs/greenfoot-main.jar') // Greenfoot sources
}

application {
    mainClass = 'wildfire.WildfireLauncher'
}

tasks {
    wrapper {
        gradleVersion = '9.7.0'
        distributionType = Wrapper.DistributionType.BIN
    }

    jar {
        manifest.attributes 'Main-Class': application.mainClass
        from(zipTree(file('libs/greenfoot-main.jar'))) // Fat jar
    }
}
